### PR TITLE
Swept's Patch

### PR DESCRIPTION
**Pull request by SweptWasTaken**
Each commit is a mod added so use that as the changelog. If you're not happy about a mod let me know but I think all of these are must-haves. Tested them on my machine and found no differences. 

The script *should* work but I only tested it on my machine so /shrug

The update script requires people to have at least gitbash installed but it means that all they have to do is clone this repo to their multi-mc instance, and then run the script everytime they launch so we can update it easily.

### CODE REVIEW

**Comment by TheChosenEvilOne** [comment]
1. Do not remove computronics, computronics is the reason why I added OpenComputers in the first place.
2. EnderIO was in the list of mods that were considered but I dropped it due to it just being another techmod.
3. Refined Storage Addons is an addon to Refined Storage not AE2.

**Comment by SweptWasTaken** [comment]
Readded computronics

EnderIO is good and i'm not going to fuck with integrated dynamics.

~~RefinedStorage is in I just accidentally~~ I guess I really didn't add refined storage...

**Comment by SweptWasTaken** [comment]
Loaded both looks like they both take the exact same time to load

**Comment by SweptWasTaken** [comment]
I swear to god if you don't merge this i'm going to cry

**Comment by TheChosenEvilOne** [comment]
> 
> 
> I swear to god if you don't merge this i'm going to cry

I guess you get to cry

**Comment by Deafult-Profile** [comment]
help

**Comment by Deafult-Profile** [comment]
help

**Comment by Deafult-Profile** [comment]
I need warp help

**Comment by TheChosenEvilOne** [comment]
Adds unneeded bloat, but I MIGHT add some of these myself to the pack.
Also missing changelog but that does not matter.

**Pull request closed without merging**
